### ISSUE TITLE
Rate limits cause tests to fail

### ISSUE THREAD

**Issue by JoshuaThompson** [jzelinskie/geddit#15]
Forked the repo, cloned it, get the following upon running "go test":

```
--- FAIL: TestSubmit (1.08s)
    reddit_test.go:26: false
    reddit_test.go:53: failed to submit
    reddit_test.go:58: failed to submit
FAIL
exit status 1
FAIL    github.com/joshuathompson/geddit    1.866s
```

Apparently due to rate limits:  "you are doing that too much. try again in x minutes.".  It appears after a little research that maybe new accounts or accounts with no karma have stricter limitations.

**Comment by jzelinskie** [comment]
These tests no longer exist. I'm going to think about the best way to test the library without hitting a live server. PyGithub for example records the request/response flow and replays them in order to mock a live server.
